# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Test
        run: make test

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: mox
          path: bin
